"""Move the entity ids an unnamed device left behind onto the device name.

Until the device carried a name, Home Assistant named it after the config
entry - the meter's address - and with `has_entity_name` every entity id was
built from that address. Renaming in the entity registry is what carries the
recorded history along: verified in
`homeassistant/components/recorder/entity_registry.py`, the recorder moves
statistics and states metadata on an entity id *rename*, so the alternative
(letting the user delete and re-add) is what loses years of readings.

Separate from `migration.py` on purpose: adoption is an all-or-nothing
invariant that refuses setup when it cannot hold, while a rename is a cosmetic
repair - one id that cannot move is not a reason to leave the meter unloadable.
Mixing the two failure policies in one module would put the weaker one within
reach of the stronger one's callers.

Only the id the old code would have generated by itself is moved: an id the
user renamed by hand, and an id adopted from the YAML block, are the user's.
"""

from __future__ import annotations

import logging

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er
from homeassistant.util import slugify

from .logging_policy import mask
from .sensor import device_name

_LOGGER = logging.getLogger(__name__)


def _generated_entity_id(entry: er.RegistryEntry, device: str) -> str:
    """The entity id Home Assistant derives for `entry` on a device called `device`.

    `_async_get_full_entity_name` joins the device name and the entity's own
    name and slugifies the result; an entity whose id differs from that was not
    named by Home Assistant, so this integration does not get to rename it.
    """
    return f"{entry.domain}.{slugify(f'{device} {entry.original_name}')}"


def async_rename_generated_entity_ids(
    hass: HomeAssistant, entry: ConfigEntry, serial: str
) -> None:
    """Rename what the entry title named; a no-op once every id has moved."""
    registry = er.async_get(hass)
    named_after_the_device = device_name(serial)
    for registry_entry in er.async_entries_for_config_entry(registry, entry.entry_id):
        if registry_entry.original_name is None:
            continue
        if registry_entry.entity_id != _generated_entity_id(
            registry_entry, entry.title
        ):
            continue
        wanted = _generated_entity_id(registry_entry, named_after_the_device)
        try:
            registry.async_update_entity(registry_entry.entity_id, new_entity_id=wanted)
        except ValueError:
            # The id this entity is leaving behind is built from the meter's
            # address, so it is the one thing this line may not print; the
            # target id and the masked unique id say which sensor stayed put.
            _LOGGER.warning(
                "Sensor %s keeps its old entity id: %s is already in use",
                mask(registry_entry.unique_id),
                wanted,
            )
